name: Tests

on:
  workflow_dispatch:

jobs:
  tests:
    name: Run Tests
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cd cacheLineSize
          make
        name: Measure Cache Line Size
      
      - run: |
          cd cacheSize
          make
        name: Measure Cache Size
